# Notebook 7 – Selecting & Filtering Data

# 1. loc

## Concept

`loc` is used to select rows and columns from a Pandas DataFrame using labels.

In simple words, when we want to select data using the row label or column name, we use `loc`.

## Simple Example

Suppose we have student information containing Name, Age, Marks and City.

If we want to select the student at a particular index or select a particular column by its name, we can use `loc`.

## Business Example

A company can use `loc` to select specific customer records or particular columns such as Customer Name, Age or Salary.

## AI/ML Use Case

In Machine Learning, `loc` can be used during data preprocessing to select required features or specific records from a dataset.

In [1]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Sourav", "Rahul", "Amit", "Riya"],
    "Age": [20, 21, 19, 22],
    "Marks": [85, 90, 75, 88],
    "City": ["Kolkata", "Delhi", "Mumbai", "Chennai"]
})

df

     Name  Age  Marks     City
0  Sourav   20     85  Kolkata
1   Rahul   21     90    Delhi
2    Amit   19     75   Mumbai
3    Riya   22     88  Chennai

In [2]:
df.loc[1]

Name     Rahul
Age         21
Marks       90
City     Delhi
Name: 1, dtype: object

## Explanation

`df.loc[1]` selects the row whose index label is `1`.

We can also select a particular column:

`df.loc[:, "Name"]`

Here:

- `:` means all rows.
- `"Name"` means the Name column.

So `loc` is mainly used when we want to select data using labels.

In [3]:
df.loc[:, "Name"]

0    Sourav
1     Rahul
2      Amit
3      Riya
Name: Name, dtype: object

# 2. iloc

## Concept

`iloc` is used to select rows and columns based on their integer position.

The main difference is:

- `loc` → selects using labels
- `iloc` → selects using positions

Python indexing starts from 0, so the first row has position 0.

## Simple Example

If we want to select the second row of a DataFrame, its position is 1. Therefore, we can use `iloc[1]`.

## Business Example

A company may use `iloc` when it wants to work with a particular position of rows or columns without depending on their labels.

## AI/ML Use Case

`iloc` can be useful while selecting particular rows or columns from datasets during data preprocessing.

In [4]:
df.iloc[1]

Name     Rahul
Age         21
Marks       90
City     Delhi
Name: 1, dtype: object

## Explanation

`df.iloc[1]` selects the row at position 1.

Since indexing starts from 0:

- Position 0 → first row
- Position 1 → second row
- Position 2 → third row

We can also select multiple rows and columns using positions.

In [5]:
df.iloc[:2, :2]

     Name  Age
0  Sourav   20
1   Rahul   21

Here `:2` selects positions 0 and 1.

Therefore, the first two rows and first two columns are selected.

# 3.Boolean Indexing

## Concept

Boolean Indexing is used to select data based on a condition.

The condition produces `True` or `False`.

Only the rows where the condition is `True` are selected.

## Simple Example

Suppose we want to find students who scored more than 80 marks.

We can create a condition:

`Marks > 80`

The students satisfying this condition will be selected.

## Business Example

A company can use Boolean Indexing to find customers whose purchase amount is greater than a particular value.

## AI/ML Use Case

Boolean Indexing is commonly used during data cleaning and preprocessing to select records that satisfy specific conditions.

In [6]:
df[df["Marks"] > 80]

     Name  Age  Marks     City
0  Sourav   20     85  Kolkata
1   Rahul   21     90    Delhi
3    Riya   22     88  Chennai

## Explanation

The condition:

`df["Marks"] > 80`

checks every value in the Marks column.

The result will be:

- 85 → True
- 90 → True
- 75 → False
- 88 → True

Only the rows having `True` are returned.

# 4.Filtering Rows

## Concept

Filtering rows means selecting only the rows that satisfy a particular condition.

It helps us focus only on the data that we need.

## Simple Example

Suppose we want to select students whose age is greater than or equal to 20.

## Business Example

A company may filter customers whose age is above 25 or whose purchase amount is greater than ₹10,000.

## AI/ML Use Case

Filtering rows can be used before model training to remove unwanted records or select a particular group of data.

In [7]:
filtered_df = df[df["Age"] >= 20]

filtered_df

     Name  Age  Marks     City
0  Sourav   20     85  Kolkata
1   Rahul   21     90    Delhi
3    Riya   22     88  Chennai

## Explanation

The condition:

`df["Age"] >= 20`

checks every student's age.

Only students whose age is 20 or greater are included in the result.

This is useful when we don't need the complete dataset and only want a specific group of records.

# 5. query()

## Concept

`query()` is a Pandas method used to filter rows by writing a condition inside a string.

It provides a simple and readable way to filter DataFrame rows.

## Simple Example

If we want students whose marks are greater than 80, we can write:

`df.query("Marks > 80")`

## Business Example

A business can use `query()` to find customers with high purchase amounts or employees with salaries above a certain value.

## AI/ML Use Case

`query()` can be used during data preprocessing to quickly select records that satisfy particular conditions.

In [8]:
result = df.query("Marks > 80")

result

     Name  Age  Marks     City
0  Sourav   20     85  Kolkata
1   Rahul   21     90    Delhi
3    Riya   22     88  Chennai

## Explanation

`query("Marks > 80")` checks the Marks column and returns only those rows where Marks are greater than 80.

It is another way of performing filtering.

For example:

`df[df["Marks"] > 80]`

and

`df.query("Marks > 80")`

perform the same basic filtering operation.

# 6. isin()

## Concept

`isin()` is used to check whether values in a column are present in a given list.

It is useful when we want to select multiple specific values.

## Simple Example

Suppose we want to select students whose names are either Sourav or Riya.

We can use `isin()` with a list of names.

## Business Example

A company may want to select customers from specific cities such as Kolkata, Delhi and Mumbai.

## AI/ML Use Case

`isin()` can be used to select specific categories or groups of records while preparing data for analysis or machine learning.

In [9]:
result = df[df["Name"].isin(["Sourav", "Riya"])]

result

     Name  Age  Marks     City
0  Sourav   20     85  Kolkata
3    Riya   22     88  Chennai

## Explanation

`isin()` checks whether each Name exists in the given list:

`["Sourav", "Riya"]`

If the name is present in the list, the condition becomes `True`.

Only those rows are selected.

# 6. between()

## Concept

`between()` is used to select values that fall within a specific range.

By default, the starting and ending values are included.

## Simple Example

Suppose we want to select students whose marks are between 80 and 90.

We can use `between(80, 90)`.

## Business Example

A company can use `between()` to select customers whose purchase amount falls between ₹5,000 and ₹10,000.

## AI/ML Use Case

`between()` can be used to select a specific range of values during data preprocessing and exploratory data analysis.

In [10]:
result = df[df["Marks"].between(80, 90)]

result

     Name  Age  Marks     City
0  Sourav   20     85  Kolkata
1   Rahul   21     90    Delhi
3    Riya   22     88  Chennai

## Explanation

`between(80, 90)` checks whether each value is between 80 and 90.

In this example:

- 85 → selected
- 90 → selected
- 75 → not selected
- 88 → selected

The starting and ending values are included by default.

# 8. Sorting Data

## Concept

Sorting means arranging data in a particular order.

In Pandas, `sort_values()` is used to sort rows according to a column.

We can sort data in ascending or descending order.

## Simple Example

Suppose we want to arrange students according to their marks from lowest to highest.

## Business Example

A company can sort products according to price, employees according to salary, or customers according to purchase amount.

## AI/ML Use Case

Sorting can be useful during data analysis to identify highest or lowest values and understand the distribution of important features.

In [11]:
result = df.sort_values("Marks")

result

     Name  Age  Marks     City
2    Amit   19     75   Mumbai
0  Sourav   20     85  Kolkata
3    Riya   22     88  Chennai
1   Rahul   21     90    Delhi

## Explanation

`sort_values("Marks")` sorts the DataFrame according to the Marks column.

By default, the data is sorted in ascending order.

That means the smallest mark comes first and the largest mark comes last.

In [12]:
result = df.sort_values("Marks", ascending=False)

result

     Name  Age  Marks     City
1   Rahul   21     90    Delhi
3    Riya   22     88  Chennai
0  Sourav   20     85  Kolkata
2    Amit   19     75   Mumbai

## Descending Order

When `ascending=False` is used, the data is arranged from the largest value to the smallest value.

So the student with the highest marks appears first.