# Notebook 8 – Data Manipulation

# 1. Rename Columns

## Concept

Renaming columns means changing the existing column names of a DataFrame to names that are easier to understand or work with.

In Pandas, we can use the `rename()` method to change column names.

## Simple Example

Suppose our dataset has a column named `Marks_Obtained`. We can rename it to simply `Marks` to make the dataset easier to understand.

## Business Example

A company may receive a dataset with complicated column names such as `cust_nm` and `cust_age`. These can be renamed to `Customer_Name` and `Customer_Age`.

## AI/ML Use Case

Renaming columns helps make feature names clear and readable during data preprocessing and machine learning.

In [1]:
import pandas as pd

df = pd.DataFrame({
    "Student_Name": ["Sourav", "Rahul", "Amit", "Riya"],
    "Student_Age": [20, 21, 19, 22],
    "Marks_Obtained": [85, 90, 75, 88]
})

df

  Student_Name  Student_Age  Marks_Obtained
0       Sourav           20              85
1        Rahul           21              90
2         Amit           19              75
3         Riya           22              88

In [2]:
df = df.rename(columns={
    "Student_Name": "Name",
    "Student_Age": "Age",
    "Marks_Obtained": "Marks"
})

df

     Name  Age  Marks
0  Sourav   20     85
1   Rahul   21     90
2    Amit   19     75
3    Riya   22     88

## Explanation

`rename()` is used to change the column names.

Here:

- `Student_Name` became `Name`
- `Student_Age` became `Age`
- `Marks_Obtained` became `Marks`

The actual data inside the columns does not change.

# 2.Drop Rows

## Concept

Dropping rows means removing unwanted rows from a DataFrame.

Pandas provides the `drop()` method to remove rows using their index.

## Simple Example

If a dataset contains an incorrect or unwanted student record, we can remove that row.

## Business Example

A company may remove records that are no longer required or contain invalid information.

## AI/ML Use Case

Unwanted or incorrect records can negatively affect a machine learning model, so removing them can be part of data preprocessing.

In [3]:
df = pd.DataFrame({
    "Name": ["Sourav", "Rahul", "Amit", "Riya"],
    "Age": [20, 21, 19, 22],
    "Marks": [85, 90, 75, 88]
})

df

     Name  Age  Marks
0  Sourav   20     85
1   Rahul   21     90
2    Amit   19     75
3    Riya   22     88

In [4]:
df = df.drop(2)

df

     Name  Age  Marks
0  Sourav   20     85
1   Rahul   21     90
3    Riya   22     88

## Explanation

`drop(2)` removes the row with index `2`.

In our dataset, index `2` belongs to Amit, so Amit's row is removed.

The remaining rows stay unchanged.

# 3. Drop Columns

## Concept

Dropping columns means removing columns that are not required from a DataFrame.

We can use the `drop()` method with `axis=1` or `columns=`.

## Simple Example

If we don't need the Age column for our analysis, we can remove it.

## Business Example

A business dataset may contain unnecessary columns such as internal IDs or unused information.

## AI/ML Use Case

Removing unnecessary features can reduce dataset complexity and can help during feature selection.

In [5]:
df = pd.DataFrame({
    "Name": ["Sourav", "Rahul", "Amit"],
    "Age": [20, 21, 19],
    "Marks": [85, 90, 75]
})

df = df.drop(columns=["Age"])

df

     Name  Marks
0  Sourav     85
1   Rahul     90
2    Amit     75

## Explanation

`drop(columns=["Age"])` removes the Age column from the DataFrame.

Only the Name and Marks columns remain.

# 4. Insert Columns

## Concept

Inserting a column means adding a new column at a specific position in a DataFrame.

Pandas provides the `insert()` method for this.

## Simple Example

Suppose we already have Name and Marks and want to insert a new Age column between them.

## Business Example

A company can insert a new feature such as Customer_Age into an existing customer dataset.

## AI/ML Use Case

New features can be added to a dataset during feature engineering.

In [6]:
df = pd.DataFrame({
    "Name": ["Sourav", "Rahul", "Amit"],
    "Marks": [85, 90, 75]
})

df.insert(1, "Age", [20, 21, 19])

df

     Name  Age  Marks
0  Sourav   20     85
1   Rahul   21     90
2    Amit   19     75

## Explanation

`insert()` takes three main values:

- `1` → position where the column should be inserted
- `"Age"` → name of the new column
- `[20, 21, 19]` → values of the column

Therefore, Age is inserted between Name and Marks.

#5. assign()

## Concept

`assign()` is used to create new columns or modify existing columns in a DataFrame.

It returns a new DataFrame instead of directly changing the original DataFrame.

## Simple Example

Suppose we have Marks and want to create a new column called `Passed` based on marks.

## Business Example

A company can create a new column such as Profit from Revenue and Cost.

## AI/ML Use Case

`assign()` can be useful during feature engineering when creating new features from existing columns.

In [7]:
df = pd.DataFrame({
    "Name": ["Sourav", "Rahul", "Amit"],
    "Marks": [85, 90, 35]
})

new_df = df.assign(
    Passed=df["Marks"] >= 40
)

new_df

     Name  Marks  Passed
0  Sourav     85    True
1   Rahul     90    True
2    Amit     35   False

## Explanation

`assign()` creates a new column called `Passed`.

The condition checks whether Marks are greater than or equal to 40.

If the condition is True, the student has passed.

# 6. apply()

## Concept

`apply()` is used to apply a function to values in a Pandas Series or DataFrame.

It is useful when we want to perform the same operation on multiple values.

## Simple Example

Suppose we want to increase every student's marks by 5.

We can create a function and apply it to the Marks column.

## Business Example

A company may apply a calculation to every employee's salary or every customer's purchase amount.

## AI/ML Use Case

`apply()` can be used for data transformation and feature engineering before training a model.

In [8]:
df = pd.DataFrame({
    "Name": ["Sourav", "Rahul", "Amit"],
    "Marks": [85, 90, 75]
})

def add_five(x):
    return x + 5

df["Updated_Marks"] = df["Marks"].apply(add_five)

df

     Name  Marks  Updated_Marks
0  Sourav     85             90
1   Rahul     90             95
2    Amit     75             80

## Explanation

The `add_five()` function adds 5 to a value.

`apply(add_five)` applies this function to every value in the Marks column.

Therefore, every student's marks increase by 5.

# 7. map()

## Concept

`map()` is mainly used with a Pandas Series to transform values or replace values according to a mapping.

It is useful when we want to convert one value into another value.

## Simple Example

Suppose a dataset stores gender as `M` and `F`.

We can use `map()` to convert:

- M → Male
- F → Female

## Business Example

A company may have short codes for departments or customer categories and use `map()` to convert them into readable names.

## AI/ML Use Case

`map()` can be useful for converting categorical values into meaningful values during data preprocessing.

In [9]:
df = pd.DataFrame({
    "Name": ["Sourav", "Rahul", "Amit"],
    "Gender": ["M", "M", "M"]
})

df["Gender"] = df["Gender"].map({
    "M": "Male",
    "F": "Female"
})

df

     Name Gender
0  Sourav   Male
1   Rahul   Male
2    Amit   Male

## Explanation

The dictionary tells Pandas how to convert the values.

`M` is converted to `Male`.

`F` would be converted to `Female`.

`map()` is useful when we have a specific mapping between old and new values.

# 8. replace()

## Concept

`replace()` is used to replace existing values in a DataFrame or Series with new values.

Unlike `map()`, `replace()` can directly replace specified values without requiring every possible value to be mapped.

## Simple Example

Suppose a dataset contains `Unknown` as a value and we want to replace it with `Not Available`.

## Business Example

A company may replace incorrect labels, spelling mistakes, or placeholder values in customer data.

## AI/ML Use Case

`replace()` can be useful during data cleaning to correct inconsistent or unwanted values.

In [10]:
df = pd.DataFrame({
    "Name": ["Sourav", "Rahul", "Amit"],
    "City": ["Kolkata", "Unknown", "Delhi"]
})

df["City"] = df["City"].replace("Unknown", "Not Available")

df

     Name           City
0  Sourav        Kolkata
1   Rahul  Not Available
2    Amit          Delhi

## Explanation

`replace()` searches for the value `Unknown` and replaces it with `Not Available`.

This is useful when cleaning inconsistent or placeholder data.

# 9. Duplicate Handling

## Concept

Duplicate data means the same record appears more than once in a dataset.

Duplicate records can make analysis incorrect because the same information may be counted multiple times.

Pandas provides `duplicated()` to identify duplicates and `drop_duplicates()` to remove them.

## Simple Example

Suppose the same student record is present twice.

We can identify and remove the duplicate record.

## Business Example

A company may accidentally store the same customer multiple times. Duplicate handling helps maintain clean customer records.

## AI/ML Use Case

Duplicate records can affect statistical analysis and machine learning models. Removing duplicates helps create a cleaner dataset.

In [11]:
df = pd.DataFrame({
    "Name": ["Sourav", "Rahul", "Amit", "Rahul"],
    "Age": [20, 21, 19, 21],
    "Marks": [85, 90, 75, 90]
})

df

     Name  Age  Marks
0  Sourav   20     85
1   Rahul   21     90
2    Amit   19     75
3   Rahul   21     90

In [12]:
df.duplicated()

0    False
1    False
2    False
3     True
dtype: bool

## Explanation

`duplicated()` checks whether each row is a duplicate of a previous row.

It returns:

- `False` → row is not a duplicate
- `True` → row is a duplicate

In [13]:
df = df.drop_duplicates()

df

     Name  Age  Marks
0  Sourav   20     85
1   Rahul   21     90
2    Amit   19     75

## Explanation

`drop_duplicates()` removes duplicate rows.

In our example, Rahul's record appears twice, so one duplicate record is removed.